[package]
name = "p72"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = "0.16.20"
getrandom = "0.2"
hex = "0.4"

[[bin]]
name = "ring_enc"
path = "bin/ring_enc.rs"

[[bin]]
name = "ring_dec"
path = "bin/ring_dec.rs"
